/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_des_centres (void);
GtkWidget* create_authentification (void);
GtkWidget* create_Menu_principal (void);
GtkWidget* create_ajout_centre (void);
GtkWidget* create_modifier_centre (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_Rechercher_un_centre (void);
GtkWidget* create_inscription (void);
GtkWidget* create_selection (void);
GtkWidget* create_authentification__entraineur (void);
