/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Menu_Principal (void);
GtkWidget* create_Menu_Admin (void);
GtkWidget* create_Interface_Admin (void);
GtkWidget* create_AD_Modifier (void);
GtkWidget* create_AD_Ajouter (void);
GtkWidget* create_AD_Supprimer (void);
GtkWidget* create_SUPP_CONFIRMATION (void);
GtkWidget* create_AD_Rechercher (void);
GtkWidget* create_AD_Liste_des_recherche_ (void);
GtkWidget* create_AD_Effectuer_un_nouveau_recherche (void);
GtkWidget* create_Login_membre (void);
GtkWidget* create_S_sinscrire____un_cours_ (void);
